### PR TITLE
Convert Readme to Markdown

### PR DESCRIPTION
**Pull request by xeruf**

### CODE REVIEW

**Comment by Xerus2000** [comment]
Anyone alive here?

**Comment by Xerus2000** [comment]
@pts is there anything blocking you from merging this?

**Comment by pts** [comment]
Thank you for preparing this pull request!

There is no technical reason (except that edits to README.txt in the meantime need to be merged manually). I'm not convinced that the benefits justify the costs of maintaining a Markdown-formatted README. Also I was busy with other aspects of my life. Sorry that the priority of this one isn't as high as it could be.

**Comment by Xerus2000** [comment]
How does it increase the costs to maintain it as markdown rather than text? Any reasonable IDE I know supports very comfortable editing of Markdown, and the viewing experience is a lot better, while the syntax adjustments are miniscule. At least that is my personal experience.

**Comment by pts** [comment]
My experience with Markdown: my text editor (which I use for developing pdfsizeopt) doesn't have Markdown support. Most of the time I can write correct Markdown in any editor, but I always have to double-check the rendering in another window. This adds maintenance work for any future changes I'll be making to `README.md`. Currently, compared with other options I can spend my free time on, I'm reluctant to pay that price.

**Comment by Xerus2000** [comment]
I just had a look at the current Readme, and it is really hard to navigate through, you can not link to sections etc. Markdown is really convenient for that. Of course the choice is up to you, but it makes the project instantly look more attractive.
Furthermore, it doesn't look like you frequently change something, so there isn't even any maintenance overhead.

**Comment by pts** [comment]
Thank you for your work on this!

I've done the conversion myself, the result is in https://github.com/pts/pdfsizeopt/commit/137fa64f27de922b3beb270939aa31cf73fdd173

**Pull request closed without merging**
